name: 'Build and Publish devcontainer image' 
 
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Print Ref Info
        run: |
          echo "inputs.glueops_codespace_tag: ${{ inputs.glueops_codespace_tag }}"
          echo "event.workflow_run.head_branch: ${{ github.event.workflow_run.head_branch }}"
          echo "event.workflow_run.head_sha: ${{ github.event.workflow_run.head_sha }}"
          echo "github.ref: ${{ github.ref }}"
          echo "event_name: ${{ github.event_name }}"
          
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.glueops_codespace_tag || github.event.workflow_run.head_sha }}

      - name: Log in to Docker Registry
        uses: docker/login-action@06fb636fac595d6fb4b28a5dfcb21a6f5091859c # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Variables for Tags
        uses: rlespinasse/github-slug-action@e6f261660910b273384c5c42b17a0217881b217a # v5.6.0

      - name: Build and run dev container task
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3
        with:
          imageName: ghcr.io/${{ env.GITHUB_REPOSITORY_OWNER_PART_SLUG }}/${{ env.GITHUB_REPOSITORY_NAME_PART_SLUG }}
          imageTag: ${{ env.GITHUB_REF_SLUG }},latest
          push: always
        env:
          VERSION: "${{ env.GITHUB_REF_SLUG }}"
