name: Packer build AWS

on:
  workflow_run:
    workflows: ["Build and Publish devcontainer image"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232 # v3.1.0
        id: setup
        with:
          version: 1.11.2

      - name: Run `packer init`
        id: init
        run: packer init aws.pkr.hcl

      - name: Run `packer build`
        id: build
        run: packer build -var glueops_codespaces_container_tag=${{ github.event.workflow_run.head_branch }} aws.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
