name: Packer build Hetzner

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Setup `packer`
        uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232 # v3.1.0
        id: setup
        with:
          version: 1.11.2

      - name: Run `packer init`
        id: init
        run: packer init hetzner.pkr.hcl

      - name: Run `packer build stage`
        id: build
        run: packer build -var glueops_codespaces_container_tag=v0.56.0 hetzner.pkr.hcl
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN_STAGE }}

      - name: Run `packer build prod`
        id: build
        run: packer build -var glueops_codespaces_container_tag=v0.56.0 hetzner.pkr.hcl
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN_PROD }}
