name: Packer build qemu

on:
  workflow_run:
    workflows: ["Build and Publish devcontainer image"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      glueops_codespace_tag:
        description: 'Enter the github.com/glueops/codespaces tag to use (e.g. v0.60.0)'
        required: false

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: codespaces
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.glueops_codespace_tag || github.event.workflow_run.head_sha }}

      - name: Setup packer
        uses: hashicorp/setup-packer@1aa358be5cf73883762b302a3a03abd66e75b232 # v3.1.0
        id: setup
        with:
          version: 1.11.2

      - name: Generate image password
        run: echo "IMAGE_PASSWORD=$(openssl rand -base64 16)" >> $GITHUB_ENV

      - name: Generate cloud-init iso
        run: |
          sudo apt install genisoimage
          echo '#cloud-config
          chpasswd:
            expire: False
            users:
            - {name: debian, password: '"$IMAGE_PASSWORD"', type: text}
          ssh_pwauth: True' > user-data
          echo 'instance-id: iid-local01
          local-hostname: localhost' > meta-data
          genisoimage -output ci-data.iso -volid cidata -joliet -rock user-data meta-data
      
      - name: Install qemu
        run: sudo apt-get update && sudo apt-get install qemu-system -y
      
      - name: Run packer init
        id: init
        run: packer init qemu.pkr.hcl

      - name: Run packer build
        id: build
        run: packer build -var glueops_codespaces_container_tag=${{ inputs.glueops_codespace_tag || github.event.workflow_run.head_branch }} -var image_password=${{ env.IMAGE_PASSWORD }} qemu.pkr.hcl


      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64 

      - name: Upload .qcow2 to S3
        run: |
          aws s3 cp images/${{ github.event.workflow_run.head_branch }}.qcow2 s3://${{ secrets.S3_BUCKET }}/${{ github.event.workflow_run.head_branch }}.qcow2 --acl public-read
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.S3_BUCKET_REGION }}


      - name: Split qcow2 image into 1024M files
        run: |
           mv images/${{ inputs.glueops_codespace_tag || github.event.workflow_run.head_branch }}.qcow2 .
           tar -cvf ${{ inputs.glueops_codespace_tag || github.event.workflow_run.head_branch }}.qcow2.tar ${{ inputs.glueops_codespace_tag || github.event.workflow_run.head_branch }}.qcow2
           split -b 1024M ${{ inputs.glueops_codespace_tag || github.event.workflow_run.head_branch }}.qcow2.tar ${{ inputs.glueops_codespace_tag || github.event.workflow_run.head_branch }}.qcow2.tar.part_

      - name: Upload *.qcow2.tar.part_* files to GitHub Releases as an Asset
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.qcow2.tar.part_*"
          tag_name: ${{ inputs.glueops_codespace_tag || github.event.workflow_run.head_branch }}    
